name: Build and deploy Node.js app to Azure Web App - condtrack928

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install backend dependencies
        run: |
          cd back-end
          npm install

      - name: Install frontend dependencies
        run: |
          cd Intro-TCC
          npm install

      - name: Build frontend project
        run: |
          cd Intro-TCC
          npm run build

      - name: Criar .env no back-end com secrets
        run: |
          cat <<EOF > back-end/.env
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_NAME=${{ secrets.DB_NAME }}
          DB_USER=${{ secrets.DB_USER }}
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=${{ secrets.DB_PORT }}
          DB_DIALECT=${{ secrets.DB_DIALECT }}
          DB_LOGGING=${{ secrets.DB_LOGGING }}
          SESSION_TOKEN=${{ secrets.SESSION_TOKEN }}
          SENDINBLUE_API_TOKEN=${{ secrets.SENDINBLUE_API_TOKEN }}
          SENDER_EMAIL=${{ secrets.SENDER_EMAIL }}
          SENDER_NAME=${{ secrets.SENDER_NAME }}
          SECRET_KEY_JWT=${{ secrets.SECRET_KEY_JWT }}
          NODE_ENV=production
          EOF

      - name: Zip backend + frontend para deployment
        run: |
          zip -r release.zip back-end Intro-TCC -x "**/node_modules/**" "**/.git/**" "*.zip"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8D88D1D3E6F7452B8B0AC02FBDA94BF0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_112184721D1D406E997429A3D5DD3BD1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EAC349A3DDF14DA9922EB5C87E969A83 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'condtrack928'
          slot-name: 'Production'
          package: .
